### ISSUE TITLE
Créer une page index.html en guise de hub + description de chaque page

### ISSUE THREAD

**Issue by ipante** [MPR329/D3_ISH#1]
Cette page enverra vers les différentes visualisations, chacune dotée de sa propre page.
Chaque visualisation doit se voit accompagnée de sa légende (explication de ce que l'on voit/ peut voir).

**Comment by MPR329** [comment]
Ajout d'un index qui renvoie aux différentes visualisations + encadré pour chaque visualisation avec une explication de ce que l'on voit/peut voir
