### ISSUE TITLE
Couleur dans les word-cloud

### ISSUE THREAD

**Issue by ipante** [MPR329/D3_ISH#3]
Préciser le sens de cette coloration et la supprimer, si elle n'est liée à aucune variable.

**Comment by MPR329** [comment]
Les différentes couleurs pour les mots n'étaient pas nécessaire et pouvaient conduire à de fausses interprétations de la visualisation. La seule variable d'interprétation est la taille des mots.

**Comment by MPR329** [comment]
Couleur des mots fixée à rouge
